create or replace task REFINE_TASK
	schedule='1 minute'
	USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE='XSMALL'
	COMMENT='2.  ELT Process New Transactions in Landing/Staging Table into a more Normalized/Refined Table (flattens JSON payloads)'
	when SYSTEM$STREAM_HAS_DATA('ADWKS_SD_PERSON_STAGING_VIEW_STREAM')
	as MERGE into FINAL_SD_PERSON as tgt USING (select distinct X.* from ADWKS_SD_PERSON_STAGING X inner join ADWKS_SD_PERSON_STAGING_VIEW_STREAM Y on X.BUSINESSENTITYID = Y.BUSINESSENTITYID ) as src
on tgt.ROWGUID = src.ROWGUID
    WHEN MATCHED THEN UPDATE set tgt.BUSINESSENTITYID = src.BUSINESSENTITYID
    , tgt.PERSONTYPE = src.PERSONTYPE
    , tgt.NAMESTYLE = src.NAMESTYLE
    , tgt.TITLE = src.TITLE
    , tgt.FIRSTNAME = src.FIRSTNAME
    , tgt.MIDDLENAME = src.MIDDLENAME
    , tgt.LASTNAME = src.LASTNAME
    , tgt.SUFFIX = src.SUFFIX
    , tgt.EMAILPROMOTION = src.EMAILPROMOTION
    , tgt.ADDITIONALCONTACTINFO = src.ADDITIONALCONTACTINFO
    , tgt.DEMOGRAPHICS = src.DEMOGRAPHICS
    , tgt.MODIFIEDDATE = src.MODIFIEDDATE
    , tgt.SYS_OPERATION_TYPE = src.SYS_OPERATION_TYPE
    , tgt.SYS_OPERATION_TIME = src.SYS_OPERATION_TIME
    , tgt.SYS_OPERATION_OWNER = src.SYS_OPERATION_OWNER
    , tgt.SYS_TRANSACTION_ID = src.SYS_TRANSACTION_ID
    , tgt.HEXID = MD5(src.ROWGUID)
    , tgt.RANDOMVAR = RANDOM()
    WHEN NOT MATCHED THEN INSERT  (HEXID, RANDOMVAR, BUSINESSENTITYID, PERSONTYPE, NAMESTYLE, TITLE, FIRSTNAME, MIDDLENAME, LASTNAME, SUFFIX, EMAILPROMOTION, ADDITIONALCONTACTINFO, DEMOGRAPHICS, ROWGUID, MODIFIEDDATE, SYS_OPERATION_TYPE, SYS_OPERATION_TIME, SYS_OPERATION_OWNER, SYS_TRANSACTION_ID ) values (MD5(src.ROWGUID), RANDOM(), src.BUSINESSENTITYID, src.PERSONTYPE, src.NAMESTYLE, src.TITLE, src.FIRSTNAME, src.MIDDLENAME, src.LASTNAME, src.SUFFIX, src.EMAILPROMOTION, src.ADDITIONALCONTACTINFO, src.DEMOGRAPHICS, src.ROWGUID, src.MODIFIEDDATE, src.SYS_OPERATION_TYPE, src.SYS_OPERATION_TIME, src.SYS_OPERATION_OWNER, src.SYS_TRANSACTION_ID);