create or replace TABLE ADWKS_SD_EMAILADDRESS (
	BUSINESSENTITYID NUMBER(38,0) NOT NULL,
	EMAILADDRESSID NUMBER(38,0) NOT NULL,
	EMAILADDRESS VARCHAR(2000),
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	TEST_NEW_COLUMN2 NUMBER(38,0),
	SYS_OPERATION_TYPE VARCHAR(1),
	SYS_OPERATION_TIME TIMESTAMP_NTZ(9),
	SYS_OPERATION_OWNER VARCHAR(256),
	SYS_TRANSACTION_ID VARCHAR(100)
);