create or replace TABLE ADWKS_SD_PASSWORD (
	BUSINESSENTITYID NUMBER(38,0) NOT NULL,
	PASSWORDHASH VARCHAR(128),
	PASSWORDSALT VARCHAR(10),
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	SYS_OPERATION_TYPE VARCHAR(1),
	SYS_OPERATION_TIME TIMESTAMP_NTZ(9),
	SYS_OPERATION_OWNER VARCHAR(256),
	SYS_TRANSACTION_ID VARCHAR(100)
);