create or replace TABLE INFO_BUSINESSENTITYADDRESS (
	BUSINESSENTITYID_OLD NUMBER(38,0),
	BUSINESSENTITYID NUMBER(38,0),
	ADDRESSID_OLD NUMBER(38,0),
	ADDRESSID NUMBER(38,0),
	ADDRESSTYPEID_OLD NUMBER(38,0),
	ADDRESSTYPEID NUMBER(38,0),
	ROWGUID_OLD VARCHAR(36),
	ROWGUID VARCHAR(36),
	MODIFIEDDATE_OLD TIMESTAMP_NTZ(3),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	INFA_OPERATION_TYPE VARCHAR(1),
	INFA_OPERATION_TIME TIMESTAMP_NTZ(9),
	INFA_OPERATION_OWNER VARCHAR(256),
	INFA_TRANSACTION_ID VARCHAR(100),
	INFA_OPERATION_SEQUENCE NUMBER(20,0)
);