create or replace TABLE PRODUCTION_WORKORDER (
	WORKORDERID NUMBER(38,0) NOT NULL,
	PRODUCTID NUMBER(38,0),
	ORDERQTY NUMBER(38,0),
	SCRAPPEDQTY NUMBER(38,0),
	STARTDATE TIMESTAMP_NTZ(3),
	ENDDATE TIMESTAMP_NTZ(3),
	DUEDATE TIMESTAMP_NTZ(3),
	SCRAPREASONID NUMBER(38,0),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_PRODUCTION_WORKORDER_PK_WORKORDER_WORKORDERID primary key (WORKORDERID)
);