create or replace TABLE PRODUCTION_LOCATION (
	LOCATIONID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(200),
	COSTRATE NUMBER(10,4),
	AVAILABILITY NUMBER(8,2),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_PRODUCTION_LOCATION_PK_LOCATION_LOCATIONID primary key (LOCATIONID)
);