create or replace TABLE PRODUCTION_CULTURE (
	CULTUREID VARCHAR(24) NOT NULL,
	NAME VARCHAR(200),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_PRODUCTION_CULTURE_PK_CULTURE_CULTUREID primary key (CULTUREID)
);