create or replace TABLE PRODUCTION_SCRAPREASON (
	SCRAPREASONID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(200),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_PRODUCTION_SCRAPREASON_PK_SCRAPREASON_SCRAPREASONID primary key (SCRAPREASONID)
);