create or replace TABLE PRODUCTION_PRODUCTCATEGORY (
	PRODUCTCATEGORYID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(200),
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_PRODUCTION_PRODUCTCATEGORY_PK_PRODUCTCATEGORY_PRODUCTCATEGORYID primary key (PRODUCTCATEGORYID)
);