create or replace TABLE PRODUCTION_BILLOFMATERIALS (
	BILLOFMATERIALSID NUMBER(38,0) NOT NULL,
	PRODUCTASSEMBLYID NUMBER(38,0),
	COMPONENTID NUMBER(38,0),
	STARTDATE TIMESTAMP_NTZ(3),
	ENDDATE TIMESTAMP_NTZ(3),
	UNITMEASURECODE VARCHAR(12),
	BOMLEVEL NUMBER(38,0),
	PERASSEMBLYQTY NUMBER(8,2),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_PRODUCTION_BILLOFMATERIALS_PK_BILLOFMATERIALS_BILLOFMATERIALSID primary key (BILLOFMATERIALSID)
);