create or replace TABLE PRODUCTION_PRODUCTREVIEW (
	PRODUCTREVIEWID NUMBER(38,0) NOT NULL,
	PRODUCTID NUMBER(38,0),
	REVIEWERNAME VARCHAR(200),
	REVIEWDATE TIMESTAMP_NTZ(3),
	EMAILADDRESS VARCHAR(200),
	RATING NUMBER(38,0),
	COMMENTS VARCHAR(15400),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_PRODUCTION_PRODUCTREVIEW_PK_PRODUCTREVIEW_PRODUCTREVIEWID primary key (PRODUCTREVIEWID)
);