create or replace TABLE PRODUCTION_PRODUCTDESCRIPTION (
	PRODUCTDESCRIPTIONID NUMBER(38,0) NOT NULL,
	DESCRIPTION VARCHAR(1600),
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_PRODUCTION_PRODUCTDESCRIPTION_PK_PRODUCTDESCRIPTION_PRODUCTDESCRIPTIONID primary key (PRODUCTDESCRIPTIONID)
);