create or replace TABLE PURCHASING_SHIPMETHOD (
	SHIPMETHODID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(200),
	SHIPBASE NUMBER(19,4),
	SHIPRATE NUMBER(19,4),
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_PURCHASING_SHIPMETHOD_PK_SHIPMETHOD_SHIPMETHODID primary key (SHIPMETHODID)
);