create or replace TABLE SALES_SALESTAXRATE (
	SALESTAXRATEID NUMBER(38,0) NOT NULL,
	STATEPROVINCEID NUMBER(38,0),
	TAXTYPE NUMBER(38,0),
	TAXRATE NUMBER(10,4),
	NAME VARCHAR(200),
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_SALES_SALESTAXRATE_PK_SALESTAXRATE_SALESTAXRATEID primary key (SALESTAXRATEID)
);