create or replace TABLE SALES_SPECIALOFFER (
	SPECIALOFFERID NUMBER(38,0) NOT NULL,
	DESCRIPTION VARCHAR(1020),
	DISCOUNTPCT NUMBER(10,4),
	TYPE VARCHAR(200),
	CATEGORY VARCHAR(200),
	STARTDATE TIMESTAMP_NTZ(3),
	ENDDATE TIMESTAMP_NTZ(3),
	MINQTY NUMBER(38,0),
	MAXQTY NUMBER(38,0),
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_SALES_SPECIALOFFER_PK_SPECIALOFFER_SPECIALOFFERID primary key (SPECIALOFFERID)
);