create or replace TABLE SALES_SALESTERRITORY (
	TERRITORYID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(200),
	COUNTRYREGIONCODE VARCHAR(12),
	"GROUP" VARCHAR(200),
	SALESYTD NUMBER(19,4),
	SALESLASTYEAR NUMBER(19,4),
	COSTYTD NUMBER(19,4),
	COSTLASTYEAR NUMBER(19,4),
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_SALES_SALESTERRITORY_PK_SALESTERRITORY_TERRITORYID primary key (TERRITORYID)
);