create or replace TABLE SALES_PERSONCREDITCARD (
	BUSINESSENTITYID NUMBER(38,0) NOT NULL,
	CREDITCARDID NUMBER(38,0) NOT NULL,
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_SALES_PERSONCREDITCARD_PK_PERSONCREDITCARD_BUSINESSENTITYID_CREDITCARDID primary key (BUSINESSENTITYID, CREDITCARDID)
);