create or replace TABLE SALES_CUSTOMER (
	CUSTOMERID NUMBER(38,0) NOT NULL,
	PERSONID NUMBER(38,0),
	STOREID NUMBER(38,0),
	TERRITORYID NUMBER(38,0),
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_SALES_CUSTOMER_PK_CUSTOMER_CUSTOMERID primary key (CUSTOMERID)
);