create or replace TABLE SALES_CURRENCY (
	CURRENCYCODE VARCHAR(12) NOT NULL,
	NAME VARCHAR(200),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_SALES_CURRENCY_PK_CURRENCY_CURRENCYCODE primary key (CURRENCYCODE)
);