create or replace TABLE ADWKS_SD_BUSINESSENTITY_LOG (
	OP_XID VARCHAR(100),
	OP_CODE VARCHAR(1),
	OP_CMT_SCN NUMBER(20,0),
	OP_CMT_TIME TIMESTAMP_NTZ(9),
	OP_NUM_IN_TX NUMBER(20,0),
	OP_KEY_LEVEL NUMBER(6,0),
	OP_ROOT_KEY_ROWID VARCHAR(100),
	OPERATION_OWNER VARCHAR(100),
	BUSINESSENTITYID_OLD NUMBER(38,0),
	BUSINESSENTITYID_NEW NUMBER(38,0),
	ROWGUID_OLD VARCHAR(36),
	ROWGUID_NEW VARCHAR(36),
	MODIFIEDDATE_OLD TIMESTAMP_NTZ(3),
	MODIFIEDDATE_NEW TIMESTAMP_NTZ(3)
);