create or replace TABLE CRIMSON_WPPHILANTHROPICGIFTCATEGORY (
	ID VARCHAR(36) NOT NULL,
	WPPHILANTHROPICGIFTID VARCHAR(36),
	PHILANTHROPICGIFTCATEGORYID VARCHAR(36),
	ADDEDBYID VARCHAR(36),
	CHANGEDBYID VARCHAR(36),
	DATEADDED TIMESTAMP_NTZ(3),
	DATECHANGED TIMESTAMP_NTZ(3),
	TS BINARY(8),
	SEQUENCE NUMBER(38,0),
	constraint PK_CRIMSON_WPPHILANTHROPICGIFTCATEGORY_PK_WPPHILANTHROPICGIFTCATEGORY primary key (ID)
);