create or replace TABLE INFO_CONTACTTYPE (
	CONTACTTYPEID_OLD NUMBER(38,0),
	CONTACTTYPEID NUMBER(38,0),
	NAME_OLD VARCHAR(200),
	NAME VARCHAR(200),
	MODIFIEDDATE_OLD TIMESTAMP_NTZ(3),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	INFA_OPERATION_TYPE VARCHAR(1),
	INFA_OPERATION_TIME TIMESTAMP_NTZ(9),
	INFA_OPERATION_OWNER VARCHAR(256),
	INFA_TRANSACTION_ID VARCHAR(100),
	INFA_OPERATION_SEQUENCE NUMBER(20,0)
);