create or replace TABLE PRODUCTION_WORKORDERROUTING (
	WORKORDERID NUMBER(38,0) NOT NULL,
	PRODUCTID NUMBER(38,0) NOT NULL,
	OPERATIONSEQUENCE NUMBER(38,0) NOT NULL,
	LOCATIONID NUMBER(38,0),
	SCHEDULEDSTARTDATE TIMESTAMP_NTZ(3),
	SCHEDULEDENDDATE TIMESTAMP_NTZ(3),
	ACTUALSTARTDATE TIMESTAMP_NTZ(3),
	ACTUALENDDATE TIMESTAMP_NTZ(3),
	ACTUALRESOURCEHRS NUMBER(9,4),
	PLANNEDCOST NUMBER(19,4),
	ACTUALCOST NUMBER(19,4),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_PRODUCTION_WORKORDERROUTING_PK_WORKORDERROUTING_WORKORDERID_PRODUCTID_OPERATIONSEQUENCE primary key (OPERATIONSEQUENCE, PRODUCTID, WORKORDERID)
);