create or replace TABLE PRODUCTION_PRODUCTCOSTHISTORY (
	PRODUCTID NUMBER(38,0) NOT NULL,
	STARTDATE TIMESTAMP_NTZ(3) NOT NULL,
	ENDDATE TIMESTAMP_NTZ(3),
	STANDARDCOST NUMBER(19,4),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_PRODUCTION_PRODUCTCOSTHISTORY_PK_PRODUCTCOSTHISTORY_PRODUCTID_STARTDATE primary key (PRODUCTID, STARTDATE)
);