create or replace TABLE PRODUCTION_PRODUCTMODELPRODUCTDESCRIPTIONCULTURE (
	PRODUCTMODELID NUMBER(38,0) NOT NULL,
	PRODUCTDESCRIPTIONID NUMBER(38,0) NOT NULL,
	CULTUREID VARCHAR(24) NOT NULL,
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_PRODUCTION_PRODUCTMODELPRODUCTDESCRIPTIONCULTURE_PK_PRODUCTMODELPRODUCTDESCRIPTIONCULTURE_PRODUCTMODELID_PRODUCTDESCRIPTIONID_CULTUREID primary key (CULTUREID, PRODUCTDESCRIPTIONID, PRODUCTMODELID)
);