create or replace TABLE PRODUCTION_TRANSACTIONHISTORYARCHIVE (
	TRANSACTIONID NUMBER(38,0) NOT NULL,
	PRODUCTID NUMBER(38,0),
	REFERENCEORDERID NUMBER(38,0),
	REFERENCEORDERLINEID NUMBER(38,0),
	TRANSACTIONDATE TIMESTAMP_NTZ(3),
	TRANSACTIONTYPE VARCHAR(4),
	QUANTITY NUMBER(38,0),
	ACTUALCOST NUMBER(19,4),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_PRODUCTION_TRANSACTIONHISTORYARCHIVE_PK_TRANSACTIONHISTORYARCHIVE_TRANSACTIONID primary key (TRANSACTIONID)
);