create or replace TABLE PRODUCTION_PRODUCTSUBCATEGORY (
	PRODUCTSUBCATEGORYID NUMBER(38,0) NOT NULL,
	PRODUCTCATEGORYID NUMBER(38,0),
	NAME VARCHAR(200),
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_PRODUCTION_PRODUCTSUBCATEGORY_PK_PRODUCTSUBCATEGORY_PRODUCTSUBCATEGORYID primary key (PRODUCTSUBCATEGORYID)
);