create or replace TABLE PRODUCTION_PRODUCTPHOTO (
	PRODUCTPHOTOID NUMBER(38,0) NOT NULL,
	THUMBNAILPHOTO BINARY(8388608),
	THUMBNAILPHOTOFILENAME VARCHAR(200),
	LARGEPHOTO BINARY(8388608),
	LARGEPHOTOFILENAME VARCHAR(200),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_PRODUCTION_PRODUCTPHOTO_PK_PRODUCTPHOTO_PRODUCTPHOTOID primary key (PRODUCTPHOTOID)
);