create or replace TABLE PRODUCTION_PRODUCTMODELILLUSTRATION (
	PRODUCTMODELID NUMBER(38,0) NOT NULL,
	ILLUSTRATIONID NUMBER(38,0) NOT NULL,
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_PRODUCTION_PRODUCTMODELILLUSTRATION_PK_PRODUCTMODELILLUSTRATION_PRODUCTMODELID_ILLUSTRATIONID primary key (ILLUSTRATIONID, PRODUCTMODELID)
);