create or replace TABLE PRODUCTION_PRODUCTPRODUCTPHOTO (
	PRODUCTID NUMBER(38,0) NOT NULL,
	PRODUCTPHOTOID NUMBER(38,0) NOT NULL,
	PRIMARY BOOLEAN,
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_PRODUCTION_PRODUCTPRODUCTPHOTO_PK_PRODUCTPRODUCTPHOTO_PRODUCTID_PRODUCTPHOTOID primary key (PRODUCTID, PRODUCTPHOTOID)
);