create or replace TABLE PRODUCTION_UNITMEASURE (
	UNITMEASURECODE VARCHAR(12) NOT NULL,
	NAME VARCHAR(200),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_PRODUCTION_UNITMEASURE_PK_UNITMEASURE_UNITMEASURECODE primary key (UNITMEASURECODE)
);