create or replace TABLE PRODUCTION_PRODUCTMODEL (
	PRODUCTMODELID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(200),
	CATALOGDESCRIPTION VARCHAR(16777216) COLLATE 'utf8',
	INSTRUCTIONS VARCHAR(16777216) COLLATE 'utf8',
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_PRODUCTION_PRODUCTMODEL_PK_PRODUCTMODEL_PRODUCTMODELID primary key (PRODUCTMODELID)
);