create or replace TABLE PURCHASING_PRODUCTVENDOR (
	PRODUCTID NUMBER(38,0) NOT NULL,
	BUSINESSENTITYID NUMBER(38,0) NOT NULL,
	AVERAGELEADTIME NUMBER(38,0),
	STANDARDPRICE NUMBER(19,4),
	LASTRECEIPTCOST NUMBER(19,4),
	LASTRECEIPTDATE TIMESTAMP_NTZ(3),
	MINORDERQTY NUMBER(38,0),
	MAXORDERQTY NUMBER(38,0),
	ONORDERQTY NUMBER(38,0),
	UNITMEASURECODE VARCHAR(12),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_PURCHASING_PRODUCTVENDOR_PK_PRODUCTVENDOR_PRODUCTID_BUSINESSENTITYID primary key (BUSINESSENTITYID, PRODUCTID)
);