create or replace TABLE PURCHASING_VENDOR (
	BUSINESSENTITYID NUMBER(38,0) NOT NULL,
	ACCOUNTNUMBER VARCHAR(60),
	NAME VARCHAR(200),
	CREDITRATING NUMBER(38,0),
	PREFERREDVENDORSTATUS BOOLEAN,
	ACTIVEFLAG BOOLEAN,
	PURCHASINGWEBSERVICEURL VARCHAR(4096),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_PURCHASING_VENDOR_PK_VENDOR_BUSINESSENTITYID primary key (BUSINESSENTITYID)
);