create or replace TABLE PURCHASING_PURCHASEORDERDETAIL (
	PURCHASEORDERID NUMBER(38,0) NOT NULL,
	PURCHASEORDERDETAILID NUMBER(38,0) NOT NULL,
	DUEDATE TIMESTAMP_NTZ(3),
	ORDERQTY NUMBER(38,0),
	PRODUCTID NUMBER(38,0),
	UNITPRICE NUMBER(19,4),
	RECEIVEDQTY NUMBER(8,2),
	REJECTEDQTY NUMBER(8,2),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_PURCHASING_PURCHASEORDERDETAIL_PK_PURCHASEORDERDETAIL_PURCHASEORDERID_PURCHASEORDERDETAILID primary key (PURCHASEORDERDETAILID, PURCHASEORDERID)
);