create or replace TABLE SALES_SALESREASON (
	SALESREASONID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(200),
	REASONTYPE VARCHAR(200),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_SALES_SALESREASON_PK_SALESREASON_SALESREASONID primary key (SALESREASONID)
);