create or replace TABLE SALES_SALESPERSONQUOTAHISTORY (
	BUSINESSENTITYID NUMBER(38,0) NOT NULL,
	QUOTADATE TIMESTAMP_NTZ(3) NOT NULL,
	SALESQUOTA NUMBER(19,4),
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_SALES_SALESPERSONQUOTAHISTORY_PK_SALESPERSONQUOTAHISTORY_BUSINESSENTITYID_QUOTADATE primary key (BUSINESSENTITYID, QUOTADATE)
);