create or replace TABLE SALES_SALESORDERHEADERSALESREASON (
	SALESORDERID NUMBER(38,0) NOT NULL,
	SALESREASONID NUMBER(38,0) NOT NULL,
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_SALES_SALESORDERHEADERSALESREASON_PK_SALESORDERHEADERSALESREASON_SALESORDERID_SALESREASONID primary key (SALESORDERID, SALESREASONID)
);