create or replace TABLE SALES_SALESTERRITORYHISTORY (
	BUSINESSENTITYID NUMBER(38,0) NOT NULL,
	TERRITORYID NUMBER(38,0) NOT NULL,
	STARTDATE TIMESTAMP_NTZ(3) NOT NULL,
	ENDDATE TIMESTAMP_NTZ(3),
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_SALES_SALESTERRITORYHISTORY_PK_SALESTERRITORYHISTORY_BUSINESSENTITYID_STARTDATE_TERRITORYID primary key (BUSINESSENTITYID, STARTDATE, TERRITORYID)
);