create or replace TABLE SALES_CREDITCARD (
	CREDITCARDID NUMBER(38,0) NOT NULL,
	CARDTYPE VARCHAR(200),
	CARDNUMBER VARCHAR(100),
	EXPMONTH NUMBER(38,0),
	EXPYEAR NUMBER(38,0),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_SALES_CREDITCARD_PK_CREDITCARD_CREDITCARDID primary key (CREDITCARDID)
);