create or replace TABLE SALES_SALESPERSON (
	BUSINESSENTITYID NUMBER(38,0) NOT NULL,
	TERRITORYID NUMBER(38,0),
	SALESQUOTA NUMBER(19,4),
	BONUS NUMBER(19,4),
	COMMISSIONPCT NUMBER(10,4),
	SALESYTD NUMBER(19,4),
	SALESLASTYEAR NUMBER(19,4),
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_SALES_SALESPERSON_PK_SALESPERSON_BUSINESSENTITYID primary key (BUSINESSENTITYID)
);