create or replace TABLE SALES_SPECIALOFFERPRODUCT (
	SPECIALOFFERID NUMBER(38,0) NOT NULL,
	PRODUCTID NUMBER(38,0) NOT NULL,
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_SALES_SPECIALOFFERPRODUCT_PK_SPECIALOFFERPRODUCT_SPECIALOFFERID_PRODUCTID primary key (PRODUCTID, SPECIALOFFERID)
);