create or replace TABLE SALES_SHOPPINGCARTITEM (
	SHOPPINGCARTITEMID NUMBER(38,0) NOT NULL,
	SHOPPINGCARTID VARCHAR(200),
	QUANTITY NUMBER(38,0),
	PRODUCTID NUMBER(38,0),
	DATECREATED TIMESTAMP_NTZ(3),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	constraint PK_SALES_SHOPPINGCARTITEM_PK_SHOPPINGCARTITEM_SHOPPINGCARTITEMID primary key (SHOPPINGCARTITEMID)
);