create or replace TABLE PURCHASEORDERHEADER_BT (
	PURCHASEORDERID NUMBER(38,0) NOT NULL,
	REVISIONNUMBER NUMBER(38,0),
	STATUS NUMBER(38,0),
	EMPLOYEEID NUMBER(38,0),
	VENDORID NUMBER(38,0),
	SHIPMETHODID NUMBER(38,0),
	ORDERDATE TIMESTAMP_NTZ(3),
	SHIPDATE TIMESTAMP_NTZ(3),
	SUBTOTAL NUMBER(19,4),
	TAXAMT NUMBER(19,4),
	FREIGHT NUMBER(19,4),
	TOTALDUE NUMBER(19,4),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	OPERATION_TYPE VARCHAR(1),
	OPERATION_TIME TIMESTAMP_NTZ(9),
	OPERATION_OWNER VARCHAR(256),
	TRANSACTION_ID VARCHAR(100)
);