create or replace TABLE VENDOR_BT (
	BUSINESSENTITYID NUMBER(38,0) NOT NULL,
	ACCOUNTNUMBER VARCHAR(60),
	NAME VARCHAR(200),
	CREDITRATING NUMBER(38,0),
	PREFERREDVENDORSTATUS BOOLEAN,
	ACTIVEFLAG BOOLEAN,
	PURCHASINGWEBSERVICEURL VARCHAR(4096),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	OPERATION_TYPE VARCHAR(1),
	OPERATION_TIME TIMESTAMP_NTZ(9),
	OPERATION_OWNER VARCHAR(256),
	TRANSACTION_ID VARCHAR(100)
);