create or replace TABLE PERSON_BT (
	BUSINESSENTITYID NUMBER(38,0) NOT NULL,
	PERSONTYPE VARCHAR(8),
	NAMESTYLE BOOLEAN,
	TITLE VARCHAR(64),
	FIRSTNAME VARCHAR(200),
	MIDDLENAME VARCHAR(200),
	LASTNAME VARCHAR(200),
	SUFFIX VARCHAR(40),
	EMAILPROMOTION NUMBER(38,0),
	ADDITIONALCONTACTINFO VARCHAR(16777216) COLLATE 'utf8',
	DEMOGRAPHICS VARCHAR(16777216) COLLATE 'utf8',
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	SYS_OPERATION_TYPE VARCHAR(1),
	SYS_OPERATION_TIME TIMESTAMP_NTZ(9),
	SYS_OPERATION_OWNER VARCHAR(256),
	SYS_TRANSACTION_ID VARCHAR(100)
);