create or replace dynamic table DYNAMIC_SALES_CUSTOMER(
	HEXID,
	CUSTOMERID,
	PERSONID,
	STOREID,
	TERRITORYID,
	ROWGUID,
	MODIFIEDDATE
) lag = '2 minutes' warehouse = TEST_GROUP_1_WH
 as
SELECT MD5(CUSTOMERID) as HEXID, CUSTOMERID, PERSONID, STOREID, TERRITORYID, ROWGUID, MODIFIEDDATE
FROM PC_INFORMATICA_DB.PUBLIC.SALES_CUSTOMER;