create or replace database ADVENTUREWORKS;

create or replace schema HUMANRESOURCES;

create or replace schema INTERNAL;

create or replace schema PERSON;

create or replace TABLE ADDRESSTYPE_BT (
	ADDRESSTYPEID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(200),
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	SYS_OPERATION_TYPE VARCHAR(1),
	SYS_OPERATION_TIME TIMESTAMP_NTZ(9),
	SYS_OPERATION_OWNER VARCHAR(256),
	SYS_TRANSACTION_ID VARCHAR(100)
);
create or replace TABLE ADDRESS_BT (
	ADDRESSID NUMBER(38,0) NOT NULL,
	ADDRESSLINE1 VARCHAR(240),
	ADDRESSLINE2 VARCHAR(240),
	CITY VARCHAR(120),
	STATEPROVINCEID NUMBER(38,0),
	POSTALCODE VARCHAR(60),
	SPATIALLOCATION BINARY(8388608),
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	SYS_OPERATION_TYPE VARCHAR(1),
	SYS_OPERATION_TIME TIMESTAMP_NTZ(9),
	SYS_OPERATION_OWNER VARCHAR(256),
	SYS_TRANSACTION_ID VARCHAR(100)
);
create or replace TABLE BUSINESSENTITYADDRESS_BT (
	BUSINESSENTITYID NUMBER(38,0) NOT NULL,
	ADDRESSID NUMBER(38,0) NOT NULL,
	ADDRESSTYPEID NUMBER(38,0) NOT NULL,
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	SYS_OPERATION_TYPE VARCHAR(1),
	SYS_OPERATION_TIME TIMESTAMP_NTZ(9),
	SYS_OPERATION_OWNER VARCHAR(256),
	SYS_TRANSACTION_ID VARCHAR(100)
);
create or replace TABLE BUSINESSENTITYCONTACT_BT (
	BUSINESSENTITYID NUMBER(38,0) NOT NULL,
	PERSONID NUMBER(38,0) NOT NULL,
	CONTACTTYPEID NUMBER(38,0) NOT NULL,
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	SYS_OPERATION_TYPE VARCHAR(1),
	SYS_OPERATION_TIME TIMESTAMP_NTZ(9),
	SYS_OPERATION_OWNER VARCHAR(256),
	SYS_TRANSACTION_ID VARCHAR(100)
);
create or replace TABLE BUSINESSENTITY_BT (
	BUSINESSENTITYID NUMBER(38,0) NOT NULL,
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	SYS_OPERATION_TYPE VARCHAR(1),
	SYS_OPERATION_TIME TIMESTAMP_NTZ(9),
	SYS_OPERATION_OWNER VARCHAR(256),
	SYS_TRANSACTION_ID VARCHAR(100)
);
create or replace TABLE CONTACTTYPE_BT (
	CONTACTTYPEID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(200),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	SYS_OPERATION_TYPE VARCHAR(1),
	SYS_OPERATION_TIME TIMESTAMP_NTZ(9),
	SYS_OPERATION_OWNER VARCHAR(256),
	SYS_TRANSACTION_ID VARCHAR(100)
);
create or replace TABLE COUNTRYREGION_BT (
	COUNTRYREGIONCODE VARCHAR(12) NOT NULL,
	NAME VARCHAR(200),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	SYS_OPERATION_TYPE VARCHAR(1),
	SYS_OPERATION_TIME TIMESTAMP_NTZ(9),
	SYS_OPERATION_OWNER VARCHAR(256),
	SYS_TRANSACTION_ID VARCHAR(100)
);
create or replace TABLE EMAILADDRESS_BT (
	BUSINESSENTITYID NUMBER(38,0) NOT NULL,
	EMAILADDRESSID NUMBER(38,0) NOT NULL,
	EMAILADDRESS VARCHAR(2000),
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	TEST_NEW_COLUMN2 NUMBER(38,0),
	SYS_OPERATION_TYPE VARCHAR(1),
	SYS_OPERATION_TIME TIMESTAMP_NTZ(9),
	SYS_OPERATION_OWNER VARCHAR(256),
	SYS_TRANSACTION_ID VARCHAR(100)
);
create or replace TABLE INFORMATICA_CDC_RECOVERY (
	TASK_ID VARCHAR(1024) NOT NULL,
	TYPE VARCHAR(128) NOT NULL,
	SCHEMA_NAME VARCHAR(512) NOT NULL,
	TABLE_NAME VARCHAR(512) NOT NULL,
	CYCLE_NUMBER NUMBER(38,0),
	SEQUENCE VARCHAR(2048),
	primary key (TASK_ID, TYPE, SCHEMA_NAME, TABLE_NAME)
);
create or replace TABLE MYNEWTABLE_BT (
	ID NUMBER(38,0) NOT NULL,
	DESCRIPTION VARCHAR(100),
	SYS_OPERATION_TYPE VARCHAR(1),
	SYS_OPERATION_TIME TIMESTAMP_NTZ(9),
	SYS_OPERATION_OWNER VARCHAR(256),
	SYS_TRANSACTION_ID VARCHAR(100)
);
create or replace TABLE PASSWORD_BT (
	BUSINESSENTITYID NUMBER(38,0) NOT NULL,
	PASSWORDHASH VARCHAR(128),
	PASSWORDSALT VARCHAR(10),
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	SYS_OPERATION_TYPE VARCHAR(1),
	SYS_OPERATION_TIME TIMESTAMP_NTZ(9),
	SYS_OPERATION_OWNER VARCHAR(256),
	SYS_TRANSACTION_ID VARCHAR(100)
);
create or replace TABLE PERSONPHONE_BT (
	BUSINESSENTITYID NUMBER(38,0) NOT NULL,
	PHONENUMBER VARCHAR(100) NOT NULL,
	PHONENUMBERTYPEID NUMBER(38,0) NOT NULL,
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	SYS_OPERATION_TYPE VARCHAR(1),
	SYS_OPERATION_TIME TIMESTAMP_NTZ(9),
	SYS_OPERATION_OWNER VARCHAR(256),
	SYS_TRANSACTION_ID VARCHAR(100)
);
create or replace TABLE PERSON_BT (
	BUSINESSENTITYID NUMBER(38,0) NOT NULL,
	PERSONTYPE VARCHAR(8),
	NAMESTYLE BOOLEAN,
	TITLE VARCHAR(64),
	FIRSTNAME VARCHAR(200),
	MIDDLENAME VARCHAR(200),
	LASTNAME VARCHAR(200),
	SUFFIX VARCHAR(40),
	EMAILPROMOTION NUMBER(38,0),
	ADDITIONALCONTACTINFO VARCHAR(16777216) COLLATE 'utf8',
	DEMOGRAPHICS VARCHAR(16777216) COLLATE 'utf8',
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	SYS_OPERATION_TYPE VARCHAR(1),
	SYS_OPERATION_TIME TIMESTAMP_NTZ(9),
	SYS_OPERATION_OWNER VARCHAR(256),
	SYS_TRANSACTION_ID VARCHAR(100)
);
create or replace secure view ADDRESS(
	SPATIALLOCATION,
	SYS_OPERATION_TYPE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	ROWGUID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SYS_OPERATION_OWNER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	ADDRESSLINE1 WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SYS_OPERATION_TIME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	MODIFIEDDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	POSTALCODE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	ADDRESSID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	SYS_TRANSACTION_ID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	CITY WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	ADDRESSLINE2 WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	STATEPROVINCEID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC
) as
                       select SPATIALLOCATION, SYS_OPERATION_TYPE, ROWGUID, SYS_OPERATION_OWNER, ADDRESSLINE1, SYS_OPERATION_TIME, MODIFIEDDATE, POSTALCODE, ADDRESSID, SYS_TRANSACTION_ID, CITY, ADDRESSLINE2, STATEPROVINCEID
                       from PERSON.ADDRESS_BT;
create or replace secure view ADDRESSTYPE(
	ROWGUID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SYS_OPERATION_TIME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	MODIFIEDDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	ADDRESSTYPEID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	NAME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SYS_OPERATION_TYPE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SYS_TRANSACTION_ID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SYS_OPERATION_OWNER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING
) as
                       select ROWGUID, SYS_OPERATION_TIME, MODIFIEDDATE, ADDRESSTYPEID, NAME, SYS_OPERATION_TYPE, SYS_TRANSACTION_ID, SYS_OPERATION_OWNER
                       from PERSON.ADDRESSTYPE_BT;
create or replace secure view BUSINESSENTITY(
	SYS_TRANSACTION_ID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SYS_OPERATION_TYPE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	BUSINESSENTITYID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	ROWGUID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SYS_OPERATION_TIME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	MODIFIEDDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	SYS_OPERATION_OWNER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING
) as
                       select SYS_TRANSACTION_ID, SYS_OPERATION_TYPE, BUSINESSENTITYID, ROWGUID, SYS_OPERATION_TIME, MODIFIEDDATE, SYS_OPERATION_OWNER
                       from PERSON.BUSINESSENTITY_BT;
create or replace secure view BUSINESSENTITYADDRESS(
	SYS_TRANSACTION_ID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SYS_OPERATION_OWNER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	ADDRESSID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	SYS_OPERATION_TIME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	BUSINESSENTITYID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	ROWGUID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SYS_OPERATION_TYPE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	ADDRESSTYPEID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	MODIFIEDDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ
) as
                       select SYS_TRANSACTION_ID, SYS_OPERATION_OWNER, ADDRESSID, SYS_OPERATION_TIME, BUSINESSENTITYID, ROWGUID, SYS_OPERATION_TYPE, ADDRESSTYPEID, MODIFIEDDATE
                       from PERSON.BUSINESSENTITYADDRESS_BT;
create or replace secure view BUSINESSENTITYCONTACT(
	MODIFIEDDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	BUSINESSENTITYID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	SYS_OPERATION_TIME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	ROWGUID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SYS_OPERATION_TYPE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	CONTACTTYPEID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	SYS_TRANSACTION_ID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	PERSONID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	SYS_OPERATION_OWNER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING
) as
                       select MODIFIEDDATE, BUSINESSENTITYID, SYS_OPERATION_TIME, ROWGUID, SYS_OPERATION_TYPE, CONTACTTYPEID, SYS_TRANSACTION_ID, PERSONID, SYS_OPERATION_OWNER
                       from PERSON.BUSINESSENTITYCONTACT_BT;
create or replace secure view CONTACTTYPE(
	SYS_TRANSACTION_ID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	MODIFIEDDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	SYS_OPERATION_TIME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	CONTACTTYPEID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	NAME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SYS_OPERATION_OWNER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SYS_OPERATION_TYPE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING
) as
                       select SYS_TRANSACTION_ID, MODIFIEDDATE, SYS_OPERATION_TIME, CONTACTTYPEID, NAME, SYS_OPERATION_OWNER, SYS_OPERATION_TYPE
                       from PERSON.CONTACTTYPE_BT;
create or replace secure view COUNTRYREGION(
	SYS_OPERATION_OWNER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	NAME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	COUNTRYREGIONCODE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SYS_OPERATION_TIME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	SYS_TRANSACTION_ID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SYS_OPERATION_TYPE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	MODIFIEDDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ
) as
                       select SYS_OPERATION_OWNER, NAME, COUNTRYREGIONCODE, SYS_OPERATION_TIME, SYS_TRANSACTION_ID, SYS_OPERATION_TYPE, MODIFIEDDATE
                       from PERSON.COUNTRYREGION_BT;
create or replace secure view EMAILADDRESS(
	MODIFIEDDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	SYS_TRANSACTION_ID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SYS_OPERATION_TYPE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	ROWGUID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	EMAILADDRESS WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	TEST_NEW_COLUMN2 WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	BUSINESSENTITYID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	SYS_OPERATION_TIME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	SYS_OPERATION_OWNER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	EMAILADDRESSID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC
) as
                       select MODIFIEDDATE, SYS_TRANSACTION_ID, SYS_OPERATION_TYPE, ROWGUID, EMAILADDRESS, TEST_NEW_COLUMN2, BUSINESSENTITYID, SYS_OPERATION_TIME, SYS_OPERATION_OWNER, EMAILADDRESSID
                       from PERSON.EMAILADDRESS_BT;
create or replace secure view MYNEWTABLE(
	SYS_TRANSACTION_ID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SYS_OPERATION_TIME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	SYS_OPERATION_TYPE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SYS_OPERATION_OWNER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	DESCRIPTION WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	ID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC
) as
                       select SYS_TRANSACTION_ID, SYS_OPERATION_TIME, SYS_OPERATION_TYPE, SYS_OPERATION_OWNER, DESCRIPTION, ID
                       from PERSON.MYNEWTABLE_BT;
create or replace secure view PASSWORD(
	PASSWORDSALT WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SYS_TRANSACTION_ID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	BUSINESSENTITYID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	MODIFIEDDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	SYS_OPERATION_TYPE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	PASSWORDHASH WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SYS_OPERATION_OWNER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	ROWGUID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SYS_OPERATION_TIME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ
) as
                       select PASSWORDSALT, SYS_TRANSACTION_ID, BUSINESSENTITYID, MODIFIEDDATE, SYS_OPERATION_TYPE, PASSWORDHASH, SYS_OPERATION_OWNER, ROWGUID, SYS_OPERATION_TIME
                       from PERSON.PASSWORD_BT;
create or replace secure view PERSON(
	SYS_OPERATION_TIME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	PERSONTYPE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	DEMOGRAPHICS WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SYS_OPERATION_OWNER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SUFFIX WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	MIDDLENAME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	LASTNAME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	ADDITIONALCONTACTINFO WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	EMAILPROMOTION WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	SYS_OPERATION_TYPE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	FIRSTNAME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	MODIFIEDDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	TITLE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SYS_TRANSACTION_ID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	NAMESTYLE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_BOOLEAN,
	BUSINESSENTITYID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	ROWGUID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING
) as
                       select SYS_OPERATION_TIME, PERSONTYPE, DEMOGRAPHICS, SYS_OPERATION_OWNER, SUFFIX, MIDDLENAME, LASTNAME, ADDITIONALCONTACTINFO, EMAILPROMOTION, SYS_OPERATION_TYPE, FIRSTNAME, MODIFIEDDATE, TITLE, SYS_TRANSACTION_ID, NAMESTYLE, BUSINESSENTITYID, ROWGUID
                       from PERSON.PERSON_BT;
create or replace secure view PERSONPHONE(
	PHONENUMBER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SYS_OPERATION_TIME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	SYS_OPERATION_TYPE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SYS_TRANSACTION_ID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	BUSINESSENTITYID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	MODIFIEDDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	PHONENUMBERTYPEID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	SYS_OPERATION_OWNER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING
) as
                       select PHONENUMBER, SYS_OPERATION_TIME, SYS_OPERATION_TYPE, SYS_TRANSACTION_ID, BUSINESSENTITYID, MODIFIEDDATE, PHONENUMBERTYPEID, SYS_OPERATION_OWNER
                       from PERSON.PERSONPHONE_BT;
create or replace schema PRODUCTION;

create or replace schema PUBLIC;

create or replace masking policy ADVENTUREWORKS_MASKING_POLICY_BOOLEAN as (VAL BOOLEAN) 
returns BOOLEAN ->
CASE
              WHEN IS_ROLE_IN_SESSION('ADVENTUREWORKS_READONLY') then val
              ELSE NULL
            END
;
create or replace masking policy ADVENTUREWORKS_MASKING_POLICY_DATE as (VAL DATE) 
returns DATE ->
CASE
          WHEN IS_ROLE_IN_SESSION('ADVENTUREWORKS_READONLY') then val
          ELSE NULL
        END
;
create or replace masking policy ADVENTUREWORKS_MASKING_POLICY_NUMERIC as (VAL NUMBER(38,0)) 
returns NUMBER(38,0) ->
CASE
          WHEN IS_ROLE_IN_SESSION('ADVENTUREWORKS_READONLY') then val
          ELSE NULL
        END
;
create or replace masking policy ADVENTUREWORKS_MASKING_POLICY_STRING as (VAL VARCHAR(16777216)) 
returns VARCHAR(16777216) ->
CASE
              WHEN IS_ROLE_IN_SESSION('ADVENTUREWORKS_READONLY') then val
              ELSE '*******'
            END
;
create or replace masking policy ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP as (VAL TIMESTAMP_NTZ(9)) 
returns TIMESTAMP_NTZ(9) ->
CASE
          WHEN IS_ROLE_IN_SESSION('ADVENTUREWORKS_READONLY') then val
          ELSE NULL
        END
;
create or replace masking policy ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ as (VAL TIMESTAMP_NTZ(9)) 
returns TIMESTAMP_NTZ(9) ->
CASE
          WHEN IS_ROLE_IN_SESSION('ADVENTUREWORKS_READONLY') then val
          ELSE NULL
        END
;
create or replace masking policy FEM_MASKING_POLICY_BOOLEAN as (VAL BOOLEAN) 
returns BOOLEAN ->
CASE
              WHEN IS_ROLE_IN_SESSION('PRD_INFORMATICA_READONLY') then val
              ELSE NULL
            END
;
create or replace masking policy FEM_MASKING_POLICY_DATE as (VAL DATE) 
returns DATE ->
CASE
          WHEN IS_ROLE_IN_SESSION('PRD_INFORMATICA_READONLY') then val
          ELSE NULL
        END
;
create or replace masking policy FEM_MASKING_POLICY_NUMERIC as (VAL NUMBER(38,0)) 
returns NUMBER(38,0) ->
CASE
          WHEN IS_ROLE_IN_SESSION('PRD_INFORMATICA_READONLY') then val
          ELSE NULL
        END
;
create or replace masking policy FEM_MASKING_POLICY_STRING as (VAL VARCHAR(16777216)) 
returns VARCHAR(16777216) ->
CASE
              WHEN IS_ROLE_IN_SESSION('PRD_INFORMATICA_READONLY') then val
              ELSE '*******'
            END
;
create or replace masking policy FEM_MASKING_POLICY_TIMESTAMP as (VAL TIMESTAMP_NTZ(9)) 
returns TIMESTAMP_NTZ(9) ->
CASE
          WHEN IS_ROLE_IN_SESSION('PRD_INFORMATICA_READONLY') then val
          ELSE NULL
        END
;
create or replace masking policy FEM_MASKING_POLICY_TIMESTAMP_NTZ as (VAL TIMESTAMP_NTZ(9)) 
returns TIMESTAMP_NTZ(9) ->
CASE
          WHEN IS_ROLE_IN_SESSION('PRD_INFORMATICA_READONLY') then val
          ELSE NULL
        END
;
create or replace schema PURCHASING;

create or replace TABLE INFORMATICA_CDC_RECOVERY (
	TASK_ID VARCHAR(1024) NOT NULL,
	TYPE VARCHAR(128) NOT NULL,
	SCHEMA_NAME VARCHAR(512) NOT NULL,
	TABLE_NAME VARCHAR(512) NOT NULL,
	CYCLE_NUMBER NUMBER(38,0),
	SEQUENCE VARCHAR(2048),
	primary key (TASK_ID, TYPE, SCHEMA_NAME, TABLE_NAME)
);
create or replace TABLE PRODUCTVENDOR_BT (
	PRODUCTID NUMBER(38,0) NOT NULL,
	BUSINESSENTITYID NUMBER(38,0) NOT NULL,
	AVERAGELEADTIME NUMBER(38,0),
	STANDARDPRICE NUMBER(19,4),
	LASTRECEIPTCOST NUMBER(19,4),
	LASTRECEIPTDATE TIMESTAMP_NTZ(3),
	MINORDERQTY NUMBER(38,0),
	MAXORDERQTY NUMBER(38,0),
	ONORDERQTY NUMBER(38,0),
	UNITMEASURECODE VARCHAR(12),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	OPERATION_TYPE VARCHAR(1),
	OPERATION_TIME TIMESTAMP_NTZ(9),
	OPERATION_OWNER VARCHAR(256),
	TRANSACTION_ID VARCHAR(100)
);
create or replace TABLE PURCHASEORDERDETAIL_BT (
	PURCHASEORDERID NUMBER(38,0) NOT NULL,
	PURCHASEORDERDETAILID NUMBER(38,0) NOT NULL,
	DUEDATE TIMESTAMP_NTZ(3),
	ORDERQTY NUMBER(38,0),
	PRODUCTID NUMBER(38,0),
	UNITPRICE NUMBER(19,4),
	RECEIVEDQTY NUMBER(8,2),
	REJECTEDQTY NUMBER(8,2),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	OPERATION_TYPE VARCHAR(1),
	OPERATION_TIME TIMESTAMP_NTZ(9),
	OPERATION_OWNER VARCHAR(256),
	TRANSACTION_ID VARCHAR(100)
);
create or replace TABLE PURCHASEORDERHEADER_BT (
	PURCHASEORDERID NUMBER(38,0) NOT NULL,
	REVISIONNUMBER NUMBER(38,0),
	STATUS NUMBER(38,0),
	EMPLOYEEID NUMBER(38,0),
	VENDORID NUMBER(38,0),
	SHIPMETHODID NUMBER(38,0),
	ORDERDATE TIMESTAMP_NTZ(3),
	SHIPDATE TIMESTAMP_NTZ(3),
	SUBTOTAL NUMBER(19,4),
	TAXAMT NUMBER(19,4),
	FREIGHT NUMBER(19,4),
	TOTALDUE NUMBER(19,4),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	OPERATION_TYPE VARCHAR(1),
	OPERATION_TIME TIMESTAMP_NTZ(9),
	OPERATION_OWNER VARCHAR(256),
	TRANSACTION_ID VARCHAR(100)
);
create or replace TABLE SHIPMETHOD_BT (
	SHIPMETHODID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(200),
	SHIPBASE NUMBER(19,4),
	SHIPRATE NUMBER(19,4),
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	OPERATION_TYPE VARCHAR(1),
	OPERATION_TIME TIMESTAMP_NTZ(9),
	OPERATION_OWNER VARCHAR(256),
	TRANSACTION_ID VARCHAR(100)
);
create or replace TABLE VENDOR_BT (
	BUSINESSENTITYID NUMBER(38,0) NOT NULL,
	ACCOUNTNUMBER VARCHAR(60),
	NAME VARCHAR(200),
	CREDITRATING NUMBER(38,0),
	PREFERREDVENDORSTATUS BOOLEAN,
	ACTIVEFLAG BOOLEAN,
	PURCHASINGWEBSERVICEURL VARCHAR(4096),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	OPERATION_TYPE VARCHAR(1),
	OPERATION_TIME TIMESTAMP_NTZ(9),
	OPERATION_OWNER VARCHAR(256),
	TRANSACTION_ID VARCHAR(100)
);
create or replace secure view PRODUCTVENDOR(
	MAXORDERQTY WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	LASTRECEIPTCOST WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	TRANSACTION_ID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	BUSINESSENTITYID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	ONORDERQTY WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	OPERATION_TYPE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	STANDARDPRICE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	LASTRECEIPTDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	MODIFIEDDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	UNITMEASURECODE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	OPERATION_OWNER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	MINORDERQTY WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	AVERAGELEADTIME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	OPERATION_TIME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	PRODUCTID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC
) as
                       select MAXORDERQTY, LASTRECEIPTCOST, TRANSACTION_ID, BUSINESSENTITYID, ONORDERQTY, OPERATION_TYPE, STANDARDPRICE, LASTRECEIPTDATE, MODIFIEDDATE, UNITMEASURECODE, OPERATION_OWNER, MINORDERQTY, AVERAGELEADTIME, OPERATION_TIME, PRODUCTID
                       from PURCHASING.PRODUCTVENDOR_BT;
create or replace secure view PURCHASEORDERDETAIL(
	PRODUCTID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	UNITPRICE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	MODIFIEDDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	PURCHASEORDERID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	OPERATION_OWNER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	OPERATION_TYPE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	TRANSACTION_ID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	RECEIVEDQTY WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	DUEDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	OPERATION_TIME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	ORDERQTY WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	REJECTEDQTY WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	PURCHASEORDERDETAILID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC
) as
                       select PRODUCTID, UNITPRICE, MODIFIEDDATE, PURCHASEORDERID, OPERATION_OWNER, OPERATION_TYPE, TRANSACTION_ID, RECEIVEDQTY, DUEDATE, OPERATION_TIME, ORDERQTY, REJECTEDQTY, PURCHASEORDERDETAILID
                       from PURCHASING.PURCHASEORDERDETAIL_BT;
create or replace secure view PURCHASEORDERHEADER(
	SUBTOTAL WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	PURCHASEORDERID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	OPERATION_TIME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	FREIGHT WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	REVISIONNUMBER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	EMPLOYEEID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	OPERATION_OWNER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SHIPDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	TRANSACTION_ID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	ORDERDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	MODIFIEDDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	TOTALDUE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	VENDORID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	STATUS WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	TAXAMT WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	OPERATION_TYPE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SHIPMETHODID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC
) as
                       select SUBTOTAL, PURCHASEORDERID, OPERATION_TIME, FREIGHT, REVISIONNUMBER, EMPLOYEEID, OPERATION_OWNER, SHIPDATE, TRANSACTION_ID, ORDERDATE, MODIFIEDDATE, TOTALDUE, VENDORID, STATUS, TAXAMT, OPERATION_TYPE, SHIPMETHODID
                       from PURCHASING.PURCHASEORDERHEADER_BT;
create or replace secure view SHIPMETHOD(
	OPERATION_TYPE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	MODIFIEDDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	SHIPBASE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	SHIPMETHODID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	SHIPRATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	OPERATION_OWNER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	OPERATION_TIME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	NAME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	TRANSACTION_ID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	ROWGUID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING
) as
                       select OPERATION_TYPE, MODIFIEDDATE, SHIPBASE, SHIPMETHODID, SHIPRATE, OPERATION_OWNER, OPERATION_TIME, NAME, TRANSACTION_ID, ROWGUID
                       from PURCHASING.SHIPMETHOD_BT;
create or replace secure view VENDOR(
	PURCHASINGWEBSERVICEURL WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	OPERATION_TIME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	ACTIVEFLAG WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_BOOLEAN,
	OPERATION_TYPE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	MODIFIEDDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	BUSINESSENTITYID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	NAME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	CREDITRATING WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	OPERATION_OWNER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	PREFERREDVENDORSTATUS WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_BOOLEAN,
	ACCOUNTNUMBER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	TRANSACTION_ID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING
) as
                       select PURCHASINGWEBSERVICEURL, OPERATION_TIME, ACTIVEFLAG, OPERATION_TYPE, MODIFIEDDATE, BUSINESSENTITYID, NAME, CREDITRATING, OPERATION_OWNER, PREFERREDVENDORSTATUS, ACCOUNTNUMBER, TRANSACTION_ID
                       from PURCHASING.VENDOR_BT;
create or replace schema SALES;
