create or replace schema PURCHASING;

create or replace TABLE INFORMATICA_CDC_RECOVERY (
	TASK_ID VARCHAR(1024) NOT NULL,
	TYPE VARCHAR(128) NOT NULL,
	SCHEMA_NAME VARCHAR(512) NOT NULL,
	TABLE_NAME VARCHAR(512) NOT NULL,
	CYCLE_NUMBER NUMBER(38,0),
	SEQUENCE VARCHAR(2048),
	primary key (TASK_ID, TYPE, SCHEMA_NAME, TABLE_NAME)
);
create or replace TABLE PRODUCTVENDOR_BT (
	PRODUCTID NUMBER(38,0) NOT NULL,
	BUSINESSENTITYID NUMBER(38,0) NOT NULL,
	AVERAGELEADTIME NUMBER(38,0),
	STANDARDPRICE NUMBER(19,4),
	LASTRECEIPTCOST NUMBER(19,4),
	LASTRECEIPTDATE TIMESTAMP_NTZ(3),
	MINORDERQTY NUMBER(38,0),
	MAXORDERQTY NUMBER(38,0),
	ONORDERQTY NUMBER(38,0),
	UNITMEASURECODE VARCHAR(12),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	OPERATION_TYPE VARCHAR(1),
	OPERATION_TIME TIMESTAMP_NTZ(9),
	OPERATION_OWNER VARCHAR(256),
	TRANSACTION_ID VARCHAR(100)
);
create or replace TABLE PURCHASEORDERDETAIL_BT (
	PURCHASEORDERID NUMBER(38,0) NOT NULL,
	PURCHASEORDERDETAILID NUMBER(38,0) NOT NULL,
	DUEDATE TIMESTAMP_NTZ(3),
	ORDERQTY NUMBER(38,0),
	PRODUCTID NUMBER(38,0),
	UNITPRICE NUMBER(19,4),
	RECEIVEDQTY NUMBER(8,2),
	REJECTEDQTY NUMBER(8,2),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	OPERATION_TYPE VARCHAR(1),
	OPERATION_TIME TIMESTAMP_NTZ(9),
	OPERATION_OWNER VARCHAR(256),
	TRANSACTION_ID VARCHAR(100)
);
create or replace TABLE PURCHASEORDERHEADER_BT (
	PURCHASEORDERID NUMBER(38,0) NOT NULL,
	REVISIONNUMBER NUMBER(38,0),
	STATUS NUMBER(38,0),
	EMPLOYEEID NUMBER(38,0),
	VENDORID NUMBER(38,0),
	SHIPMETHODID NUMBER(38,0),
	ORDERDATE TIMESTAMP_NTZ(3),
	SHIPDATE TIMESTAMP_NTZ(3),
	SUBTOTAL NUMBER(19,4),
	TAXAMT NUMBER(19,4),
	FREIGHT NUMBER(19,4),
	TOTALDUE NUMBER(19,4),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	OPERATION_TYPE VARCHAR(1),
	OPERATION_TIME TIMESTAMP_NTZ(9),
	OPERATION_OWNER VARCHAR(256),
	TRANSACTION_ID VARCHAR(100)
);
create or replace TABLE SHIPMETHOD_BT (
	SHIPMETHODID NUMBER(38,0) NOT NULL,
	NAME VARCHAR(200),
	SHIPBASE NUMBER(19,4),
	SHIPRATE NUMBER(19,4),
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	OPERATION_TYPE VARCHAR(1),
	OPERATION_TIME TIMESTAMP_NTZ(9),
	OPERATION_OWNER VARCHAR(256),
	TRANSACTION_ID VARCHAR(100)
);
create or replace TABLE VENDOR_BT (
	BUSINESSENTITYID NUMBER(38,0) NOT NULL,
	ACCOUNTNUMBER VARCHAR(60),
	NAME VARCHAR(200),
	CREDITRATING NUMBER(38,0),
	PREFERREDVENDORSTATUS BOOLEAN,
	ACTIVEFLAG BOOLEAN,
	PURCHASINGWEBSERVICEURL VARCHAR(4096),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	OPERATION_TYPE VARCHAR(1),
	OPERATION_TIME TIMESTAMP_NTZ(9),
	OPERATION_OWNER VARCHAR(256),
	TRANSACTION_ID VARCHAR(100)
);
create or replace secure view PRODUCTVENDOR(
	MAXORDERQTY WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	LASTRECEIPTCOST WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	TRANSACTION_ID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	BUSINESSENTITYID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	ONORDERQTY WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	OPERATION_TYPE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	STANDARDPRICE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	LASTRECEIPTDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	MODIFIEDDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	UNITMEASURECODE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	OPERATION_OWNER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	MINORDERQTY WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	AVERAGELEADTIME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	OPERATION_TIME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	PRODUCTID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC
) as
                       select MAXORDERQTY, LASTRECEIPTCOST, TRANSACTION_ID, BUSINESSENTITYID, ONORDERQTY, OPERATION_TYPE, STANDARDPRICE, LASTRECEIPTDATE, MODIFIEDDATE, UNITMEASURECODE, OPERATION_OWNER, MINORDERQTY, AVERAGELEADTIME, OPERATION_TIME, PRODUCTID
                       from PURCHASING.PRODUCTVENDOR_BT;
create or replace secure view PURCHASEORDERDETAIL(
	PRODUCTID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	UNITPRICE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	MODIFIEDDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	PURCHASEORDERID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	OPERATION_OWNER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	OPERATION_TYPE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	TRANSACTION_ID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	RECEIVEDQTY WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	DUEDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	OPERATION_TIME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	ORDERQTY WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	REJECTEDQTY WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	PURCHASEORDERDETAILID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC
) as
                       select PRODUCTID, UNITPRICE, MODIFIEDDATE, PURCHASEORDERID, OPERATION_OWNER, OPERATION_TYPE, TRANSACTION_ID, RECEIVEDQTY, DUEDATE, OPERATION_TIME, ORDERQTY, REJECTEDQTY, PURCHASEORDERDETAILID
                       from PURCHASING.PURCHASEORDERDETAIL_BT;
create or replace secure view PURCHASEORDERHEADER(
	SUBTOTAL WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	PURCHASEORDERID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	OPERATION_TIME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	FREIGHT WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	REVISIONNUMBER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	EMPLOYEEID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	OPERATION_OWNER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SHIPDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	TRANSACTION_ID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	ORDERDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	MODIFIEDDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	TOTALDUE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	VENDORID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	STATUS WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	TAXAMT WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	OPERATION_TYPE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	SHIPMETHODID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC
) as
                       select SUBTOTAL, PURCHASEORDERID, OPERATION_TIME, FREIGHT, REVISIONNUMBER, EMPLOYEEID, OPERATION_OWNER, SHIPDATE, TRANSACTION_ID, ORDERDATE, MODIFIEDDATE, TOTALDUE, VENDORID, STATUS, TAXAMT, OPERATION_TYPE, SHIPMETHODID
                       from PURCHASING.PURCHASEORDERHEADER_BT;
create or replace secure view SHIPMETHOD(
	OPERATION_TYPE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	MODIFIEDDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	SHIPBASE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	SHIPMETHODID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	SHIPRATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	OPERATION_OWNER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	OPERATION_TIME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	NAME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	TRANSACTION_ID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	ROWGUID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING
) as
                       select OPERATION_TYPE, MODIFIEDDATE, SHIPBASE, SHIPMETHODID, SHIPRATE, OPERATION_OWNER, OPERATION_TIME, NAME, TRANSACTION_ID, ROWGUID
                       from PURCHASING.SHIPMETHOD_BT;
create or replace secure view VENDOR(
	PURCHASINGWEBSERVICEURL WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	OPERATION_TIME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	ACTIVEFLAG WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_BOOLEAN,
	OPERATION_TYPE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	MODIFIEDDATE WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_TIMESTAMP_NTZ,
	BUSINESSENTITYID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	NAME WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	CREDITRATING WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_NUMERIC,
	OPERATION_OWNER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	PREFERREDVENDORSTATUS WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_BOOLEAN,
	ACCOUNTNUMBER WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING,
	TRANSACTION_ID WITH MASKING POLICY ADVENTUREWORKS.PUBLIC.ADVENTUREWORKS_MASKING_POLICY_STRING
) as
                       select PURCHASINGWEBSERVICEURL, OPERATION_TIME, ACTIVEFLAG, OPERATION_TYPE, MODIFIEDDATE, BUSINESSENTITYID, NAME, CREDITRATING, OPERATION_OWNER, PREFERREDVENDORSTATUS, ACCOUNTNUMBER, TRANSACTION_ID
                       from PURCHASING.VENDOR_BT;