create or replace TABLE ADDRESS_BT (
	ADDRESSID NUMBER(38,0) NOT NULL,
	ADDRESSLINE1 VARCHAR(240),
	ADDRESSLINE2 VARCHAR(240),
	CITY VARCHAR(120),
	STATEPROVINCEID NUMBER(38,0),
	POSTALCODE VARCHAR(60),
	SPATIALLOCATION BINARY(8388608),
	ROWGUID VARCHAR(36),
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	SYS_OPERATION_TYPE VARCHAR(1),
	SYS_OPERATION_TIME TIMESTAMP_NTZ(9),
	SYS_OPERATION_OWNER VARCHAR(256),
	SYS_TRANSACTION_ID VARCHAR(100)
);