create or replace TABLE PERSONPHONE_BT (
	BUSINESSENTITYID NUMBER(38,0) NOT NULL,
	PHONENUMBER VARCHAR(100) NOT NULL,
	PHONENUMBERTYPEID NUMBER(38,0) NOT NULL,
	MODIFIEDDATE TIMESTAMP_NTZ(3),
	SYS_OPERATION_TYPE VARCHAR(1),
	SYS_OPERATION_TIME TIMESTAMP_NTZ(9),
	SYS_OPERATION_OWNER VARCHAR(256),
	SYS_TRANSACTION_ID VARCHAR(100)
);