create or replace materialized view CUSTOMER_MV(
	C_CUSTKEY,
	C_NAME WITH MASKING POLICY CRIMSON.PUBLIC.CRIMSON_MASKING_POLICY_STRING,
	C_ADDRESS,
	C_NATIONKEY,
	C_PHONE,
	C_ACCTBAL,
	C_MKTSEGMENT,
	C_COMMENT
) as 
SELECT C_CUSTKEY, C_NAME, C_ADDRESS, C_NATIONKEY, C_PHONE, C_ACCTBAL, C_MKTSEGMENT, C_COMMENT
FROM CRIMSON.PUBLIC.CUSTOMER;